package eje04.modelo.entidad;
// Generated 22/06/2015 11:50:27 AM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String idpersona;
     private String nombre;
     private String apellidoPat;
     private String apellidoMat;
     private String dni;

    public Persona() {
    }

	
    public Persona(String idpersona) {
        this.idpersona = idpersona;
    }
    public Persona(String idpersona, String nombre, String apellidoPat, String apellidoMat, String dni) {
       this.idpersona = idpersona;
       this.nombre = nombre;
       this.apellidoPat = apellidoPat;
       this.apellidoMat = apellidoMat;
       this.dni = dni;
    }
   
    public String getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(String idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPat() {
        return this.apellidoPat;
    }
    
    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }
    public String getApellidoMat() {
        return this.apellidoMat;
    }
    
    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }




}


